# Generated by Django 2.1 on 2018-08-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_edited_by',
            field=models.CharField(default='sarahkirk', max_length=50),
        ),
    ]
